package com.money.expenz.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)
val Teal80 = Color(0xFF03DAC5)
val MayaBlue = Color(0xFF58BDFF)
val RedOrange = Color(0xFFC4421A)
val Red200 = Color(0xfff297a2)
val Red300 = Color(0xffea6d7e)
val Orange = Color(0xFFF98F45)
val greenTint = Color(0xFF4eae72)
val blue = Color(0xFF2196F3)
val yellow = Color(0xFFFFCB4a)
val redTint = Color(0xFFFD6955)
val Cyan = Color(0xFF97CECC)
val Cyan80 = Color(0xFF12908E)
val DarkSeaGreen = Color(0xFF8FBC8B)
val GreenCyan = Color(0xFF16594A)
val Olive = Color(0xFF808000)
val Teal40 = Color(0xFF018786)
val SeaBlue = Color(0xFF125B7F)
val SquidInk = Color(0xFF092D40)
val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)
val Black = Color(0xFF000000)
val White = Color(0xFFFFFFFF)

// Custom Material Theme

val md_theme_light_primary = Color(0xFF6750A4)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFEADDFF)
val md_theme_light_onPrimaryContainer = Color(0xFF21005D)
val md_theme_light_secondary = Color(0xFF625B71)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE8DEF8)
val md_theme_light_onSecondaryContainer = Color(0xFF1D192B)
val md_theme_light_tertiary = Color(0xFF7D5260)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFD8E4)
val md_theme_light_onTertiaryContainer = Color(0xFF31111D)
val md_theme_light_error = Color(0xFFB3261E)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFF9DEDC)
val md_theme_light_onErrorContainer = Color(0xFF410E0B)
val md_theme_light_outline = Color(0xFF79747E)
val md_theme_light_background = Color(0xFFFEF7FF)
val md_theme_light_onBackground = Color(0xFF1D1B20)
val md_theme_light_surface = Color(0xFFFEF7FF)
val md_theme_light_onSurface = Color(0xFF1D1B20)
val md_theme_light_surfaceVariant = Color(0xFFE7E0EC)
val md_theme_light_onSurfaceVariant = Color(0xFF49454F)
val md_theme_light_inverseSurface = Color(0xFF322F35)
val md_theme_light_inverseOnSurface = Color(0xFFF5EFF7)
val md_theme_light_inversePrimary = Color(0xFFD0BCFF)
val md_theme_light_surfaceTint = Color(0xFF6750A4)
val md_theme_light_outlineVariant = Color(0xFFCAC4D0)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFD0BCFF)
val md_theme_dark_onPrimary = Color(0xFF381E72)
val md_theme_dark_primaryContainer = Color(0xFF4F378B)
val md_theme_dark_onPrimaryContainer = Color(0xFFEADDFF)
val md_theme_dark_secondary = Color(0xFFCCC2DC)
val md_theme_dark_onSecondary = Color(0xFF332D41)
val md_theme_dark_secondaryContainer = Color(0xFF4A4458)
val md_theme_dark_onSecondaryContainer = Color(0xFFE8DEF8)
val md_theme_dark_tertiary = Color(0xFFEFB8C8)
val md_theme_dark_onTertiary = Color(0xFF492532)
val md_theme_dark_tertiaryContainer = Color(0xFF633B48)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFD8E4)
val md_theme_dark_error = Color(0xFFF2B8B5)
val md_theme_dark_onError = Color(0xFF601410)
val md_theme_dark_errorContainer = Color(0xFF8C1D18)
val md_theme_dark_onErrorContainer = Color(0xFFF9DEDC)
val md_theme_dark_outline = Color(0xFF938F99)
val md_theme_dark_background = Color(0xFF141218)
val md_theme_dark_onBackground = Color(0xFFE6E0E9)
val md_theme_dark_surface = Color(0xFF141218)
val md_theme_dark_onSurface = Color(0xFFE6E0E9)
val md_theme_dark_surfaceVariant = Color(0xFF49454F)
val md_theme_dark_onSurfaceVariant = Color(0xFFCAC4D0)
val md_theme_dark_inverseSurface = Color(0xFFE6E0E9)
val md_theme_dark_inverseOnSurface = Color(0xFF322F35)
val md_theme_dark_inversePrimary = Color(0xFF6750A4)
val md_theme_dark_surfaceTint = Color(0xFFD0BCFF)
val md_theme_dark_outlineVariant = Color(0xFF49454F)
val md_theme_dark_scrim = Color(0xFF000000)

val seed = Color(0xFF6750A4)

// Green
/*
val md_theme_light_primary = Color(0xFF1E6C2F)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFA5F5A8)
val md_theme_light_onPrimaryContainer = Color(0xFF002107)
val md_theme_light_secondary = Color(0xFF516350)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD4E8D0)
val md_theme_light_onSecondaryContainer = Color(0xFF101F10)
val md_theme_light_tertiary = Color(0xFF39656C)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFBCEBF2)
val md_theme_light_onTertiaryContainer = Color(0xFF001F24)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFCFDF7)
val md_theme_light_onBackground = Color(0xFF1A1C19)
val md_theme_light_outline = Color(0xFF72796F)
val md_theme_light_inverseOnSurface = Color(0xFFF0F1EB)
val md_theme_light_inverseSurface = Color(0xFF2F312D)
val md_theme_light_inversePrimary = Color(0xFF8AD88E)
val md_theme_light_surfaceTint = Color(0xFF1E6C2F)
val md_theme_light_outlineVariant = Color(0xFFC2C9BD)
val md_theme_light_scrim = Color(0xFF000000)
val md_theme_light_surface = Color(0xFFF9FAF4)
val md_theme_light_onSurface = Color(0xFF1A1C19)
val md_theme_light_surfaceVariant = Color(0xFFDEE5D9)
val md_theme_light_onSurfaceVariant = Color(0xFF424940)

val md_theme_dark_primary = Color(0xFF8AD88E)
val md_theme_dark_onPrimary = Color(0xFF003911)
val md_theme_dark_primaryContainer = Color(0xFF00531C)
val md_theme_dark_onPrimaryContainer = Color(0xFFA5F5A8)
val md_theme_dark_secondary = Color(0xFFB9CCB5)
val md_theme_dark_onSecondary = Color(0xFF243424)
val md_theme_dark_secondaryContainer = Color(0xFF3A4B39)
val md_theme_dark_onSecondaryContainer = Color(0xFFD4E8D0)
val md_theme_dark_tertiary = Color(0xFFA1CED6)
val md_theme_dark_onTertiary = Color(0xFF00363C)
val md_theme_dark_tertiaryContainer = Color(0xFF1F4D53)
val md_theme_dark_onTertiaryContainer = Color(0xFFBCEBF2)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1A1C19)
val md_theme_dark_onBackground = Color(0xFFE2E3DD)
val md_theme_dark_outline = Color(0xFF8C9389)
val md_theme_dark_inverseOnSurface = Color(0xFF1A1C19)
val md_theme_dark_inverseSurface = Color(0xFFE2E3DD)
val md_theme_dark_inversePrimary = Color(0xFF1E6C2F)
val md_theme_dark_surfaceTint = Color(0xFF8AD88E)
val md_theme_dark_outlineVariant = Color(0xFF424940)
val md_theme_dark_scrim = Color(0xFF000000)
val md_theme_dark_surface = Color(0xFF111411)
val md_theme_dark_onSurface = Color(0xFFC6C7C1)
val md_theme_dark_surfaceVariant = Color(0xFF424940)
val md_theme_dark_onSurfaceVariant = Color(0xFFC2C9BD)

val seed = Color(0xFF285C2F)
*/

// Wine

/*
val md_theme_light_primary = Color(0xFFA1317C)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFD8EA)
val md_theme_light_onPrimaryContainer = Color(0xFF3C002B)
val md_theme_light_secondary = Color(0xFF715764)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFCD9E9)
val md_theme_light_onSecondaryContainer = Color(0xFF291521)
val md_theme_light_tertiary = Color(0xFF80543C)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDBCA)
val md_theme_light_onTertiaryContainer = Color(0xFF311302)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1F1A1C)
val md_theme_light_outline = Color(0xFF827379)
val md_theme_light_inverseOnSurface = Color(0xFFF9EEF1)
val md_theme_light_inverseSurface = Color(0xFF352F31)
val md_theme_light_inversePrimary = Color(0xFFFFAEDB)
val md_theme_light_surfaceTint = Color(0xFFA1317C)
val md_theme_light_outlineVariant = Color(0xFFD3C2C9)
val md_theme_light_scrim = Color(0xFF000000)
val md_theme_light_surface = Color(0xFFFFF8F8)
val md_theme_light_onSurface = Color(0xFF1F1A1C)
val md_theme_light_surfaceVariant = Color(0xFFF0DEE5)
val md_theme_light_onSurfaceVariant = Color(0xFF504349)

val md_theme_dark_primary = Color(0xFFFFAEDB)
val md_theme_dark_onPrimary = Color(0xFF610048)
val md_theme_dark_primaryContainer = Color(0xFF831563)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFD8EA)
val md_theme_dark_secondary = Color(0xFFDFBECD)
val md_theme_dark_onSecondary = Color(0xFF402A36)
val md_theme_dark_secondaryContainer = Color(0xFF58404C)
val md_theme_dark_onSecondaryContainer = Color(0xFFFCD9E9)
val md_theme_dark_tertiary = Color(0xFFF3BA9D)
val md_theme_dark_onTertiary = Color(0xFF4A2713)
val md_theme_dark_tertiaryContainer = Color(0xFF653D27)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDBCA)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1F1A1C)
val md_theme_dark_onBackground = Color(0xFFEAE0E3)
val md_theme_dark_outline = Color(0xFF9C8D93)
val md_theme_dark_inverseOnSurface = Color(0xFF1F1A1C)
val md_theme_dark_inverseSurface = Color(0xFFEAE0E3)
val md_theme_dark_inversePrimary = Color(0xFFA1317C)
val md_theme_dark_surfaceTint = Color(0xFFFFAEDB)
val md_theme_dark_outlineVariant = Color(0xFF504349)
val md_theme_dark_scrim = Color(0xFF000000)
val md_theme_dark_surface = Color(0xFF171214)
val md_theme_dark_onSurface = Color(0xFFCEC4C7)
val md_theme_dark_surfaceVariant = Color(0xFF504349)
val md_theme_dark_onSurfaceVariant = Color(0xFFD3C2C9)


val seed = Color(0xFF7C0C5D)

*/
